import {Operations} from './Operations';
import {createPortal} from 'react-dom';
import {useEffect,useRef,useState} from 'react';
import type {AdminAction} from '../../../shared/ipc/contracts';
export function AdminPanel({close}:{close:()=>void}){
 const ref=useRef<HTMLDialogElement>(null),[users,setUsers]=useState<{email:string;enabled:boolean}[]>([]),[email,setEmail]=useState(''),[admin,setAdmin]=useState(''),[addresses,setAddresses]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function request(action:AdminAction){const result=await window.discorda!.admin(action);if(!result.ok)throw Error(result.message);return result.data;}
 async function load(){const [settings,people,network]=await Promise.all([request({kind:'settings'}),request({kind:'users'}),request({kind:'network'})]);setAdmin((settings as {adminEmail:string}).adminEmail);setUsers(people as typeof users);setAddresses((network as string[]).join('\n'));}
 async function run(action:()=>Promise<void>){if(busy)return;setBusy(true);setMessage('');try{await action();}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível concluir.');}finally{setBusy(false);}}
 useEffect(()=>{const previous=document.activeElement;const dialog=ref.current;dialog?.showModal();void run(load);return()=>{dialog?.close();if(previous instanceof HTMLElement&&previous.isConnected)previous.focus();};},[]);
 const [block,setBlock]=useState<string>();
 return createPortal(<dialog ref={ref} className="admin-dialog" aria-label="Administrar servidor" onCancel={close}><header><h2>Administrar servidor</h2><button onClick={close}>Fechar</button></header><p>Administrador principal: <strong>{admin||'Verificando…'}</strong></p><p>Esta permissão é definida na configuração privada do host e verificada pelo servidor.</p><section><h3>Pessoas autorizadas</h3><form onSubmit={e=>{e.preventDefault();void run(async()=>{await request({kind:'user',email:email.trim(),enabled:true});setEmail('');await load();setMessage('Acesso autorizado.');});}}><label>E-mail<input type="email" required maxLength={320} value={email} onChange={e=>setEmail(e.target.value)}/></label><button disabled={busy}>Autorizar pessoa</button></form><ul>{users.map(person=><li key={person.email}><span>{person.email} · {person.enabled?'Autorizado':'Bloqueado'}</span><button disabled={busy||person.email.toLowerCase()===admin.toLowerCase()} onClick={()=>{if(person.enabled)setBlock(person.email);else void run(async()=>{await request({kind:'user',email:person.email,enabled:true});await load();setMessage('Acesso autorizado.');});}}>{person.enabled?'Bloquear':'Autorizar'}</button></li>)}</ul></section>{block&&<section className="moderation-confirm" aria-label="Confirmar bloqueio"><h3>Bloquear {block}?</h3><p>As sessões serão revogadas e essa pessoa perderá o acesso ao grupo.</p><button disabled={busy} onClick={()=>void run(async()=>{await request({kind:'user',email:block,enabled:false});setBlock(undefined);await load();setMessage('Acesso bloqueado.');})}>Confirmar bloqueio</button><button disabled={busy} onClick={()=>setBlock(undefined)}>Cancelar</button></section>}<section><h3>Rede Radmin</h3><label>IPs autorizados, um por linha<textarea rows={5} value={addresses} onChange={e=>setAddresses(e.target.value)}/></label><button disabled={busy} onClick={()=>void run(async()=>{await request({kind:'networkSave',addresses:addresses.split(/\s+/).filter(Boolean)});setMessage('Lista salva. Baixe e aplique a política no computador servidor.');})}>Salvar IPs</button><button disabled={busy} onClick={()=>void run(async()=>{await request({kind:'firewall'});})}>Baixar política de Firewall</button><p>Salvar a lista não altera o Firewall. Execute o arquivo como administrador do Windows no host, após revisar.</p></section><Operations/><section><h3>Operação do host</h3><p>Para iniciar/parar serviços e criar ou restaurar backups, use o Painel do servidor no computador que hospeda o grupo. As credenciais Google continuam no painel web administrativo/Supabase.</p></section><p role="status">{busy?'Processando…':message}</p></dialog>,document.body);
}
