import {StoragePolicy} from './StoragePolicy';
import {useEffect,useState} from 'react';
interface Page {items:{id:string;messageId:string;name:string;size:number;createdAt:string}[];hasMore:boolean;usedBytes:number;limitBytes:number}
export function AttachmentStorage(){
 const [page,setPage]=useState<Page>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState<string>();
 async function load(before?:string){setBusy(true);try{const r=await window.discorda!.admin({kind:'attachments',before});if(!r.ok)throw Error(r.message);setPage(r.data as Page);setError('');}catch{setError('Não foi possível consultar os anexos. Atualize o servidor e tente novamente.');}finally{setBusy(false);}}
 useEffect(()=>{void load();},[]);
 async function remove(id:string){setBusy(true);try{const r=await window.discorda!.admin({kind:'attachmentDelete',id});if(!r.ok)throw Error(r.message);setConfirm(undefined);await load();}catch{setError('Não foi possível remover o arquivo.');}finally{setBusy(false);}}
 return <section className="attachment-storage"><h4>Arquivos do grupo</h4><StoragePolicy onClean={()=>void load()}/>{page&&<><p>{(page.usedBytes/1048576).toFixed(1)} de {Math.round(page.limitBytes/1048576)} MiB usados</p>{page.usedBytes>=page.limitBytes*.8&&<p role="status">Armazenamento acima de 80% da cota. Revise os arquivos antes de novos envios.</p>}<meter min={0} max={page.limitBytes} value={page.usedBytes}/><p>Remover um anexo libera a cota do grupo. A mensagem permanece no histórico. O tamanho físico do banco pode não diminuir imediatamente.</p><ul>{page.items.map(f=><li key={f.id}><div><strong>{f.name}</strong><small>{new Date(f.createdAt).toLocaleDateString('pt-BR')} · {(f.size/1024).toFixed(0)} KiB</small></div>{confirm===f.id?<span>Excluir permanentemente? <button disabled={busy} onClick={()=>void remove(f.id)}>Excluir arquivo</button><button onClick={()=>setConfirm(undefined)}>Manter</button></span>:<button disabled={busy} onClick={()=>setConfirm(f.id)}>Remover</button>}</li>)}</ul>{!page.items.length&&<p>Nenhum arquivo nesta página.</p>}{page.hasMore&&<button disabled={busy} onClick={()=>void load(page.items.at(-1)?.messageId)}>Ver arquivos mais antigos</button>}</>}{error&&<p role="alert">{error}</p>}<button disabled={busy} onClick={()=>void load()}>{busy?'Consultando…':'Atualizar armazenamento'}</button></section>;
}
