import {useEffect,useRef,useState} from 'react';
import {Modal} from '../../components/ui/modal';
import {scopedKey} from '../../lib/server-scope';
import type {ChatWorkspace,VoiceMember} from '../../../shared/ipc/contracts';
import type {InboxItem} from './Inbox';
type Overview={since:string;channels:{id:string;name:string;lastMessageId:string}[];pins:InboxItem[]};
export function CatchUp({workspace,onSelect,onChannel,onOpenChange}:{workspace:ChatWorkspace;onSelect:(item:InboxItem)=>void;onChannel:(id:string)=>void;onOpenChange:(open:boolean)=>void}){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[overview,setOverview]=useState<Overview>(),[items,setItems]=useState<InboxItem[]>([]),[streams,setStreams]=useState<VoiceMember[]>([]);
 const epoch=useRef(0),loading=useRef(false),key=scopedKey('last-review:'+workspace.userId),since=useRef<string|undefined>(undefined);
 useEffect(()=>{try{const saved=localStorage.getItem(key);since.current=saved&&Number.isFinite(Date.parse(saved))?saved:undefined;}catch{}},[key]);
 useEffect(()=>{onOpenChange(open);return()=>onOpenChange(false);},[open]);
 async function load(){if(loading.current)return;loading.current=true;setBusy(true);setError('');const generation=++epoch.current;
  try{const [summary,inbox,roster]=await Promise.all([window.discorda!.chat({kind:'catchUp',since:since.current}),window.discorda!.chat({kind:'inbox',unread:true}),window.discorda!.chat({kind:'voiceRoster'})]);if(generation!==epoch.current)return;if(!summary.ok||!inbox.ok)throw Error('Não foi possível carregar as novidades. Verifique se o servidor está atualizado.');
   const data=summary.data as Overview;if(!data||!Array.isArray(data.channels)||!Array.isArray(data.pins))throw Error('Atualize o servidor para consultar as novidades.');setOverview(data);setItems((inbox.data as {items:InboxItem[]}).items);if(roster.ok)setStreams((roster.data as VoiceMember[]).filter(m=>m.screenSharing));
   try{localStorage.setItem(key,new Date().toISOString());}catch{}
  }catch(e){if(generation===epoch.current)setError(e instanceof Error?e.message:'Novidades indisponíveis.');}finally{if(generation===epoch.current){loading.current=false;setBusy(false);}}
 }
 useEffect(()=>{if(!open)return;loading.current=false;void load();const off=window.discorda?.onLiveEvent(e=>{if(e.kind==='voiceRoster')setStreams(e.data.filter(m=>m.screenSharing));});return()=>{epoch.current++;off?.();};},[open]);
 const select=(item:InboxItem)=>{onSelect(item);setOpen(false);};
 return <><button className="inbox-launch" onClick={()=>setOpen(true)}>Desde sua última visita</button>{open&&<Modal label="Desde sua última visita" className="inbox-dialog catch-up-dialog" onClose={()=>setOpen(false)}><header><h2>Desde sua última visita</h2><button aria-label="Fechar novidades" onClick={()=>setOpen(false)}>×</button></header><p>Abrir este painel não marca suas mensagens como lidas. Fixadas desde {overview?new Date(overview.since).toLocaleDateString('pt-BR'):'a última consulta'}, até 30 dias.</p><button disabled={busy} onClick={()=>void load()}>Atualizar novidades</button>{error&&<p role="alert">{error}</p>}{busy&&<p role="status">Carregando novidades…</p>}<div className="catch-up-content"><h3>Ao vivo agora</h3>{streams.length?streams.map(s=><button key={s.userId} onClick={()=>{window.dispatchEvent(new CustomEvent('discorda:open-voice',{detail:s.channelId}));setOpen(false);}}>{s.name} · {workspace.voiceChannels?.find(c=>c.id===s.channelId)?.name??'Sala de voz'} · Entrar para assistir</button>):<p>Nenhuma transmissão informada pelo servidor.</p>}<h3>Canais com mensagens não lidas</h3>{overview?.channels.map(c=><button key={c.id} onClick={()=>{onChannel(c.id);setOpen(false);}}>#{c.name} · Abrir canal</button>)}{overview&&!overview.channels.length&&<p>Seus canais estão em dia.</p>}<h3>Menções e respostas</h3><div className="inbox-items">{items.map(i=><article key={i.id}><small>#{i.channelName} · {i.kind==='mention'?'Menção':i.kind==='reply'?'Resposta':'Tópico'}</small><strong>{i.authorName}</strong><p>{i.body.replace(/<@[0-9a-f-]+>/gi,'@membro')}</p><button onClick={()=>select(i)}>Abrir mensagem</button></article>)}</div>{!items.length&&overview&&<p>Nenhuma menção ou resposta pendente. A caixa de entrada contém o histórico completo.</p>}<h3>Fixadas recentemente</h3><div className="inbox-items">{overview?.pins.map(i=><article key={i.id}><small>#{i.channelName}</small><p>{i.body.replace(/<@[0-9a-f-]+>/gi,'@membro')}</p><button onClick={()=>select(i)}>Abrir fixada</button></article>)}</div>{overview&&!overview.pins.length&&<p>Nenhuma mensagem fixada nesse período.</p>}</div></Modal>}</>;
}
