import {useEffect,useState} from 'react';
import {diagnosticSummary} from './diagnostic-summary';
import type {DiagnosticReport,ChatWorkspace} from '../../../shared/ipc/contracts';
export function Diagnostics({voice,reconnect}:{voice:string;reconnect:()=>void}) {
 const [sharing,setSharing]=useState(false),[summary,setSummary]=useState(''),[channels,setChannels]=useState<ChatWorkspace['channels']>([]),[destination,setDestination]=useState(''),[sent,setSent]=useState(false);
 const [sendId]=useState(()=>crypto.randomUUID());
 async function prepare(){setBusy(true);setError('');try{const fresh=await window.discorda!.diagnostics('status');const result=await window.discorda!.chat({kind:'workspace'});if(!result.ok)throw Error(result.message);const list=(result.data as ChatWorkspace).channels;setChannels(list);setDestination(list[0]?.id??'');setSummary(diagnosticSummary(fresh));setSharing(true);}catch{setError('Não foi possível preparar o resumo.');}finally{setBusy(false);}}
 async function share(){setBusy(true);setError('');try{const result=await window.discorda!.chat({kind:'send',channelId:destination,clientId:sendId,body:summary});if(!result.ok)throw Error(result.message);setSent(true);}catch{setError('Não foi possível enviar. Tente novamente.');}finally{setBusy(false);}}
 const [report,setReport]=useState<DiagnosticReport>(),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function refresh(action:'status'|'export'='status'){setBusy(true);setError('');try{setReport(await window.discorda!.diagnostics(action));}catch{setError('Não foi possível obter o diagnóstico. Tente novamente.');}finally{setBusy(false);}}
 useEffect(()=>{void refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh();},5000);return()=>clearInterval(timer);},[]);
 return <section className="diagnostics"><p>Confira cada conexão separadamente.</p><dl><dt>Servidor</dt><dd>{report?.api==='online'?'Disponível':report?'Indisponível':'Verificando…'}</dd><dt>Compatibilidade do servidor</dt><dd>{report?.serverProtocol?`Protocolo ${report.serverProtocol}`:'Não informado por este servidor'}</dd><dt>Banco de dados</dt><dd>{report?.database==='ready'?'Disponível':report?'Indisponível':'Verificando…'}</dd><dt>Chat em tempo real</dt><dd>{report?.chat==='connected'?'Conectado':report?.chat==='reconnecting'?'Reconectando':'Desconectado'}</dd><dt>Chamada</dt><dd>{voice||'Fora de uma chamada'}</dd><dt>Tentativas do chat</dt><dd>{report?.attempts??'—'}</dd>{report?.performance&&<><dt>CPU do aplicativo</dt><dd>{report.performance.cpuPercent}%</dd><dt>Memória dos processos</dt><dd>{report.performance.memoryMiB} MiB</dd><dt>Processos</dt><dd>{report.performance.processes}</dd></>}</dl><p>A memória soma os processos e pode contar páginas compartilhadas mais de uma vez. Compare repouso, chamada e transmissão nesta máquina.</p><button disabled={busy} onClick={()=>void refresh()}>Verificar conexões</button><button disabled={busy} onClick={()=>{void window.discorda?.reconnectLive().then(()=>refresh()).catch(()=>setError('Não foi possível reconectar. Tente novamente.'));reconnect();}}>Reconectar</button><button disabled={busy} onClick={()=>void refresh('export')}>Exportar diagnóstico</button><p>O arquivo contém versão e estados de conexão. Não inclui IPs, e-mails, mensagens, nomes ou credenciais.</p><button disabled={busy||sent} onClick={()=>void prepare()}>Compartilhar diagnóstico</button>{sharing&&<div className="diagnostic-share"><h3>{sent?'Resumo enviado':'Revise antes de compartilhar'}</h3><pre>{summary}</pre>{!sent&&<><label>Canal de destino<select value={destination} disabled={busy} onChange={e=>setDestination(e.target.value)}>{channels.map(c=><option value={c.id} key={c.id}>#{c.name}</option>)}</select></label><button disabled={busy||!destination} onClick={()=>void share()}>Enviar resumo ao canal</button></>}<button disabled={busy} onClick={()=>setSharing(false)}>Fechar</button></div>}{error&&<p role="alert">{error}</p>}</section>;
}
