import {useEffect,useState} from 'react';
import type {AdminAction} from '../../../shared/ipc/contracts';
type Invite={id:string;expiresAt:string;maxUses:number;uses:number;revoked:boolean};
type Request={id:string;name:string;email:string;createdAt:string};
export function Invitations(){
 const [invites,setInvites]=useState<Invite[]>([]),[requests,setRequests]=useState<Request[]>([]),[hours,setHours]=useState(24),[maxUses,setMaxUses]=useState(5),[link,setLink]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){const [i,r]=await Promise.all([window.discorda!.admin({kind:'invites'}),window.discorda!.admin({kind:'joinRequests'})]);if(!i.ok||!r.ok||!Array.isArray(i.data)||!Array.isArray(r.data))throw Error('Não foi possível carregar convites e pedidos. Atualize o servidor se necessário.');setInvites(i.data as Invite[]);setRequests(r.data as Request[]);}
 async function run(action?:AdminAction){setBusy(true);setError('');try{if(action){const r=await window.discorda!.admin(action);if(!r.ok)throw Error(r.message);if(action.kind==='inviteCreate')setLink((r.data as {link:string}).link);}await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível concluir.');}finally{setBusy(false);}}
 useEffect(()=>{void run();},[]);
 return <section className="invitation-management"><h4>Convites e pedidos de acesso</h4><p>O Google confirma a identidade; você decide quem entra. Cada solicitação reserva um uso do convite.</p><div className="policy-fields"><label>Validade<select value={hours} onChange={e=>setHours(Number(e.target.value))}><option value={1}>1 hora</option><option value={24}>24 horas</option><option value={168}>7 dias</option></select></label><label>Limite de solicitações<input type="number" min={1} max={100} value={maxUses} onChange={e=>setMaxUses(Number(e.target.value))}/></label></div><button disabled={busy||maxUses<1||maxUses>100} onClick={()=>void run({kind:'inviteCreate',hours,maxUses})}>Criar e copiar convite</button>{link&&<label>Convite copiado · guarde o link<input readOnly value={link} onFocus={e=>e.currentTarget.select()}/></label>}<p>O link só é exibido ao criar. Revogar ou expirar também impede a aprovação de pedidos pendentes desse convite.</p><ul>{invites.map(i=><li key={i.id}><span>{i.uses}/{i.maxUses} solicitações · até {new Date(i.expiresAt).toLocaleString('pt-BR')}{i.revoked?' · Revogado':''}</span>{!i.revoked&&<button disabled={busy} onClick={()=>void run({kind:'inviteRevoke',id:i.id})}>Revogar</button>}</li>)}</ul><h4>Pedidos pendentes ({requests.length})</h4>{requests.map(r=><article key={r.id}><strong>{r.name}</strong><p>{r.email}</p><button disabled={busy} onClick={()=>void run({kind:'joinReview',id:r.id,approve:true})}>Aprovar acesso</button><button disabled={busy} onClick={()=>void run({kind:'joinReview',id:r.id,approve:false})}>Recusar</button></article>)}{!requests.length&&<p>Nenhum pedido pendente.</p>}<button disabled={busy} onClick={()=>void run()}>Atualizar pedidos</button>{error&&<p role="alert">{error}</p>}</section>;
}
