import type {Report} from '../../../shared/operations';
import {useEffect,useRef,useState} from 'react';

const size=(bytes:number|null)=>{if(bytes===null)return 'Indisponível';const unit=bytes>=1073741824?'GiB':'MiB';return (bytes/(unit==='GiB'?1073741824:1048576)).toLocaleString('pt-BR',{maximumFractionDigits:2})+' '+unit;};
const date=(value:string|null)=>value?new Date(value).toLocaleString('pt-BR'):'Sem registro';
export function Operations(){
 const loading=useRef(false);
 const [report,setReport]=useState<Report>(),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){if(loading.current)return;loading.current=true;setBusy(true);setError('');try{const result=await window.discorda!.admin({kind:'operations'});if(!result.ok)throw Error(result.message);setReport(result.data as Report);}catch(error){setError(error instanceof Error?error.message:'Falha ao consultar.');}finally{loading.current=false;setBusy(false);}}
 useEffect(()=>{void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},15000);return()=>clearInterval(timer);},[]);
 return <section className="operations-panel"><h3>Operação do servidor</h3><button disabled={busy} onClick={()=>void load()}>{busy?'Consultando…':'Atualizar indicadores'}</button><p role="status">{error}</p>{report&&<><dl className="operation-grid"><div><dt>API</dt><dd>{report.api==='online'?'Disponível':'Indisponível'}</dd></div><div><dt>Banco</dt><dd>{report.database==='ready'?'Disponível':'Indisponível'}</dd></div><div><dt>Voz e vídeo</dt><dd>{report.media==='online'?'Disponível':'Indisponível'}</dd></div><div><dt>Pessoas em chamada</dt><dd>{report.activeCalls}</dd></div><div><dt>Memória da API</dt><dd>{Math.round(report.process.memoryBytes/1048576)} MB</dd></div><div><dt>CPU média da API</dt><dd>{report.process.cpuAveragePercent}%</dd></div><div><dt>Tempo da API ativa</dt><dd>{Math.floor(report.process.uptimeSeconds/60)} min</dd></div><div><dt>Banco em disco</dt><dd>{size(report.storage.databaseBytes)}</dd></div><div><dt>Espaço disponível no volume</dt><dd>{size(report.storage.freeBytes)} de {size(report.storage.totalBytes)}</dd></div></dl><p>Indicadores são atualizados a cada 15 segundos. Uso do processo da API, não da VPS inteira. CPU é a média desde a inicialização; o espaço é o volume visível ao servidor.</p><h4>Versões e compatibilidade</h4><dl className="operation-grid"><div><dt>API (assembly)</dt><dd>{report.versions?.api??'Não informado'}</dd></div><div><dt>.NET</dt><dd>{report.versions?.runtime??'Não informado'}</dd></div><div><dt>PostgreSQL</dt><dd>{report.versions?.database??'Não informado'}</dd></div><div><dt>Protocolo</dt><dd>{report.versions?.protocol??'Servidor anterior'}</dd></div></dl>{report.storage.freeBytes!==null&&report.storage.totalBytes!==null&&report.storage.totalBytes>0&&report.storage.freeBytes/report.storage.totalBytes<0.1&&<p role="alert">Menos de 10% de espaço disponível. Verifique o armazenamento no host.</p>}<button disabled={busy} onClick={()=>{setBusy(true);void window.discorda!.admin({kind:'operationsExport'}).then(result=>{if(!result.ok)setError(result.message);}).catch(()=>setError('Não foi possível salvar o diagnóstico.')).finally(()=>setBusy(false));}}>Exportar saúde do servidor</button><p>Exporta apenas indicadores numéricos, estados e versões; sem configuração, nomes, endereços ou conteúdo de conversas.</p><h4>Backups</h4>{report.backup?<><p>{report.backup.ok?'Última execução concluída':'Última execução falhou'} · {date(report.backup.lastRun)}</p><p>Última restauração de teste registrada: {date(report.backup.lastVerified)}</p>{report.backup.lastRun&&Date.now()-Date.parse(report.backup.lastRun)>172800000&&<p role="status">O último registro de backup tem mais de 48 horas.</p>}</>:<p>Nenhum resultado de backup registrado. Configure o backup no computador servidor conforme o guia de operação.</p>}<small>Consultado em {date(report.checkedAt)}. Guarde uma cópia fora do servidor e teste a restauração periodicamente.</small></>}</section>;
}
