import {Accessibility} from '../Accessibility';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {Mic,SlidersHorizontal,Download,X,Activity,Eye,UserRound} from 'lucide-react';
export function SettingsDialog({onClose,audio,devices,updates,diagnostics,account,initialTab='audio'}:{onClose:()=>void;audio:ReactNode;devices:ReactNode;updates:ReactNode;diagnostics?:ReactNode;account?:ReactNode;initialTab?:'audio'|'devices'|'updates'|'diagnostics'|'accessibility'|'account'}){
 const ref=useRef<HTMLDialogElement>(null),content=useRef<HTMLDivElement>(null);
 const [tab,setTab]=useState<typeof initialTab>(initialTab),[version,setVersion]=useState('…');
 useEffect(()=>{const previous=document.activeElement;const dialog=ref.current;dialog?.showModal();let active=true;window.discorda?.getAppInfo().then(info=>{if(active)setVersion(info.version);}).catch(()=>{if(active)setVersion('indisponível');});return()=>{active=false;dialog?.close();if(previous instanceof HTMLElement&&previous.isConnected)previous.focus();};},[]);
 const entries=[...(account?[{id:'account' as const,label:'Minha conta',icon:UserRound}]:[]),{id:'accessibility' as const,label:'Acessibilidade',icon:Eye},{id:'audio' as const,label:'Voz e microfone',icon:Mic},{id:'devices' as const,label:'Dispositivos',icon:SlidersHorizontal},{id:'updates' as const,label:'Atualizações',icon:Download},{id:'diagnostics' as const,label:'Conexão e diagnóstico',icon:Activity}];
 return <dialog ref={ref} className="settings-dialog" aria-label="Configurações" onCancel={onClose}>
  <aside className="settings-nav"><h2>Configurações</h2><p>Seu Discorda, do seu jeito.</p><nav role="tablist" aria-orientation="vertical" aria-label="Seções de configurações">{entries.map(({id,label,icon:Icon})=><button key={id} role="tab" id={`settings-tab-${id}`} aria-controls="settings-panel" aria-selected={tab===id} tabIndex={tab===id?0:-1} onKeyDown={event=>{const index=entries.findIndex(entry=>entry.id===id);const next=event.key==='Home'?0:event.key==='End'?entries.length-1:event.key==='ArrowDown'?(index+1)%entries.length:event.key==='ArrowUp'?(index-1+entries.length)%entries.length:-1;if(next<0)return;event.preventDefault();setTab(entries[next].id);document.getElementById(`settings-tab-${entries[next].id}`)?.focus();content.current?.scrollTo({top:0});}} aria-current={tab===id?'page':undefined} onClick={()=>{setTab(id);content.current?.scrollTo({top:0});}}><Icon size={18}/>{label}</button>)}</nav><div className="settings-version"><strong>discorda.</strong><span>Versão instalada: {version}</span></div></aside>
  <div className="settings-body"><header><div><h2>{entries.find(x=>x.id===tab)?.label}</h2><p>{tab==='account'?'Seu perfil e acesso ao grupo.':tab==='accessibility'?'Deixe a leitura e a navegação confortáveis.':tab==='audio'?'Ajuste sua voz e os sons da chamada.':tab==='devices'?'Escolha seus dispositivos e confira as permissões.':tab==='diagnostics'?'Verifique o servidor, o chat e a chamada.':'Mantenha seu aplicativo atualizado.'}</p></div><button className="icon-button" aria-label="Fechar configurações" onClick={onClose}><X size={21}/></button></header><div className="settings-content" ref={content} key={tab} id="settings-panel" role="tabpanel" tabIndex={0} aria-labelledby={`settings-tab-${tab}`}>{tab==='account'?account:tab==='accessibility'?<Accessibility/>:tab==='audio'?audio:tab==='devices'?devices:tab==='diagnostics'?diagnostics:updates}</div></div>
 </dialog>;
}
