import {useEffect,useState} from 'react';
interface Policy{quotaMiB:number;retentionDays:number;version:number}
interface Preview{cutoff:string;fingerprint:string;count:number;bytes:number;hasMore:boolean;files:{name:string;size:number;createdAt:string}[]}
export function StoragePolicy({onClean}:{onClean:()=>void}){
 const [policy,setPolicy]=useState<Policy>(),[preview,setPreview]=useState<Preview>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState('');
 useEffect(()=>{void window.discorda!.admin({kind:'storagePolicy'}).then(r=>{if(r.ok)setPolicy(r.data as Policy);else setError(r.message);}).catch(()=>setError('Não foi possível consultar a política.'));},[]);
 async function run(kind:'save'|'preview'|'clean'){if(!policy)return;setBusy(true);setError('');setStatus('');try{const r=await window.discorda!.admin(kind==='save'?{kind:'storageSave',...policy}:kind==='preview'?{kind:'storagePreview'}:{kind:'storageCleanup',cutoff:preview!.cutoff,fingerprint:preview!.fingerprint});if(!r.ok)throw Error(r.message);if(kind==='save'){setPolicy(r.data as Policy);setPreview(undefined);setStatus('Política salva. Nenhum arquivo foi removido.');onClean();}else if(kind==='preview')setPreview(r.data as Preview);else{setStatus('Limpeza concluída.');setPreview(undefined);onClean();}}catch(e){setError(e instanceof Error?e.message:'Não foi possível concluir.');if(kind==='clean')setPreview(undefined);}finally{setBusy(false);}}
 return <section className="storage-policy"><h4>Política de armazenamento</h4>{policy&&<><div className="policy-fields"><label>Cota de anexos (MiB)<input type="number" min={16} max={10240} value={policy.quotaMiB} onChange={e=>{setPolicy({...policy,quotaMiB:Number(e.target.value)});setPreview(undefined);}}/></label><label>Elegíveis para limpeza após (dias)<input type="number" min={0} max={3650} value={policy.retentionDays} onChange={e=>{setPolicy({...policy,retentionDays:Number(e.target.value)});setPreview(undefined);}}/></label></div><p>Use 0 dias para manter indefinidamente. A remoção exige revisar e confirmar cada lote de até 100 arquivos. Reduzir a cota pode bloquear novos envios; não apaga os existentes.</p><button disabled={busy} onClick={()=>void run('save')}>Salvar política</button><button disabled={busy||policy.retentionDays===0} onClick={()=>void run('preview')}>Revisar limpeza da política salva</button></>}{preview&&<div className="cleanup-preview"><strong>{preview.count} arquivos · {(preview.bytes/1048576).toFixed(2)} MiB a liberar</strong><p>Confirmação válida por 5 minutos. Os arquivos serão excluídos permanentemente.</p><ul>{preview.files.map((f,i)=><li key={i}>{f.name} · {new Date(f.createdAt).toLocaleDateString('pt-BR')} · {f.size} bytes</li>)}</ul>{preview.hasMore&&<p>Há mais arquivos elegíveis; revise outro lote depois deste.</p>}<button disabled={busy||!preview.count} onClick={()=>void run('clean')}>Confirmar exclusão destes arquivos</button><button onClick={()=>setPreview(undefined)}>Cancelar limpeza</button></div>}{status&&<p role="status">{status}</p>}{error&&<p role="alert">{error}</p>}</section>;
}
